# Generated by Django 4.2.1 on 2023-05-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_remove_book_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='Books.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
